### ISSUE TITLE
Deprecated UI-1 issues overview: Annoyance-checklist for UI-2

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-long-term-issues#1]
After talking to @jacogr I'm closing all bugs and annoyances related to the old user interface in the parity repository as _wontfix_ or _stale_ because most of the stuff is not worth fixing with the new user interface on the horizon. However, I keep this list of closed issues for future reference and to allow checking these issues against the UI-2.

### Bugs:

- [ ] https://github.com/paritytech/parity/issues/5412
- [ ] https://github.com/paritytech/parity/issues/5660
- [ ] https://github.com/paritytech/parity/issues/5672
- [ ] https://github.com/paritytech/parity/issues/5706
- [ ] https://github.com/paritytech/parity/issues/5747
- [ ] https://github.com/paritytech/parity/issues/5963
- [ ] https://github.com/paritytech/parity/issues/5998
- [ ] https://github.com/paritytech/parity/issues/6082
- [ ] https://github.com/paritytech/parity/issues/6098
- [ ] https://github.com/paritytech/parity/issues/6238
- [ ] https://github.com/paritytech/parity/issues/6285
- [ ] https://github.com/paritytech/parity/issues/6336
- [ ] https://github.com/paritytech/parity/issues/6382

### Annoyances:

- [ ] https://github.com/paritytech/parity/issues/3562
- [ ] https://github.com/paritytech/parity/issues/3684
- [ ] https://github.com/paritytech/parity/issues/3925
- [ ] https://github.com/paritytech/parity/issues/4078
- [ ] https://github.com/paritytech/parity/issues/4079
- [ ] https://github.com/paritytech/parity/issues/4123
- [ ] https://github.com/paritytech/parity/issues/4185
- [ ] https://github.com/paritytech/parity/issues/4373
- [ ] https://github.com/paritytech/parity/issues/4395
- [ ] https://github.com/paritytech/parity/issues/4802
- [ ] https://github.com/paritytech/parity/issues/4963
- [ ] https://github.com/paritytech/parity/issues/4991
- [ ] https://github.com/paritytech/parity/issues/5382
- [ ] https://github.com/paritytech/parity/issues/5468
- [ ] https://github.com/paritytech/parity/issues/5472
- [ ] https://github.com/paritytech/parity/issues/5483
- [ ] https://github.com/paritytech/parity/issues/5493
- [ ] https://github.com/paritytech/parity/issues/5517
- [ ] https://github.com/paritytech/parity/issues/5638
- [ ] https://github.com/paritytech/parity/issues/5638
- [ ] https://github.com/paritytech/parity/issues/5726
- [ ] https://github.com/paritytech/parity/issues/5819
- [ ] https://github.com/paritytech/parity/issues/5920
- [ ] https://github.com/paritytech/parity/issues/6158
- [ ] https://github.com/paritytech/parity/issues/6222
- [ ] https://github.com/paritytech/parity/issues/6236
- [ ] https://github.com/paritytech/parity/issues/6261
- [ ] https://github.com/paritytech/parity/issues/6367
- [ ] https://github.com/paritytech/parity/issues/6388
- [ ] https://github.com/paritytech/parity/issues/6407
- [ ] https://github.com/paritytech/parity/issues/6451
