### ISSUE TITLE
Longterm UI-Feature-Requests

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-long-term-issues#2]
A list of all feature requests for the Parity Wallet:

- [ ] https://github.com/paritytech/parity/issues/2125
- [ ] https://github.com/paritytech/parity/issues/2143
- [ ] https://github.com/paritytech/parity/issues/2145
- [ ] https://github.com/paritytech/parity/issues/2281
- [ ] https://github.com/paritytech/parity/issues/2594
- [ ] https://github.com/paritytech/parity/issues/2928
- [ ] https://github.com/paritytech/parity/issues/3074
- [ ] https://github.com/paritytech/parity/issues/3075
- [ ] https://github.com/paritytech/parity/issues/3114
- [ ] https://github.com/paritytech/parity/issues/3180
- [ ] https://github.com/paritytech/parity/issues/3217
- [ ] https://github.com/paritytech/parity/issues/3292
- [ ] https://github.com/paritytech/parity/issues/3352
- [ ] https://github.com/paritytech/parity/issues/3408
- [ ] https://github.com/paritytech/parity/issues/3409
- [ ] https://github.com/paritytech/parity/issues/3538
- [ ] https://github.com/paritytech/parity/issues/3541
- [ ] https://github.com/paritytech/parity/issues/3542
- [ ] https://github.com/paritytech/parity/issues/3610
- [ ] https://github.com/paritytech/parity/issues/3626
- [ ] https://github.com/paritytech/parity/issues/3696
- [ ] https://github.com/paritytech/parity/issues/3802
- [ ] https://github.com/paritytech/parity/issues/3803
- [ ] https://github.com/paritytech/parity/issues/3826
- [ ] https://github.com/paritytech/parity/issues/3910
- [ ] https://github.com/paritytech/parity/issues/3941
- [ ] https://github.com/paritytech/parity/issues/3944
- [ ] https://github.com/paritytech/parity/issues/3989
- [ ] https://github.com/paritytech/parity/issues/4064
- [ ] https://github.com/paritytech/parity/issues/4072
- [ ] https://github.com/paritytech/parity/issues/4139
- [ ] https://github.com/paritytech/parity/issues/4230
- [ ] https://github.com/paritytech/parity/issues/4267
- [ ] https://github.com/paritytech/parity/issues/4282
- [ ] https://github.com/paritytech/parity/issues/4353
- [ ] https://github.com/paritytech/parity/issues/4425
- [ ] https://github.com/paritytech/parity/issues/4474
- [ ] https://github.com/paritytech/parity/issues/4500
- [ ] https://github.com/paritytech/parity/issues/4622
- [ ] https://github.com/paritytech/parity/issues/4660
- [ ] https://github.com/paritytech/parity/issues/4704
- [ ] https://github.com/paritytech/parity/issues/4707
- [ ] https://github.com/paritytech/parity/issues/4708
- [ ] https://github.com/paritytech/parity/issues/4754
- [ ] https://github.com/paritytech/parity/issues/4768
- [ ] https://github.com/paritytech/parity/issues/4793
- [ ] https://github.com/paritytech/parity/issues/4795
- [ ] https://github.com/paritytech/parity/issues/4876
- [ ] https://github.com/paritytech/parity/issues/4924
- [ ] https://github.com/paritytech/parity/issues/4925
- [ ] https://github.com/paritytech/parity/issues/4928
- [ ] https://github.com/paritytech/parity/issues/4950
- [ ] https://github.com/paritytech/parity/issues/5005
- [ ] https://github.com/paritytech/parity/issues/5007
- [ ] https://github.com/paritytech/parity/issues/5293
- [ ] https://github.com/paritytech/parity/issues/5296
- [ ] https://github.com/paritytech/parity/issues/5322
- [ ] https://github.com/paritytech/parity/issues/5344
- [ ] https://github.com/paritytech/parity/issues/5361
- [ ] https://github.com/paritytech/parity/issues/5368
- [ ] https://github.com/paritytech/parity/issues/5476
- [ ] https://github.com/paritytech/parity/issues/5491
- [ ] https://github.com/paritytech/parity/issues/5604
- [ ] https://github.com/paritytech/parity/issues/5690
- [ ] https://github.com/paritytech/parity/issues/5723
- [ ] https://github.com/paritytech/parity/issues/5724
- [ ] https://github.com/paritytech/parity/issues/5732
- [ ] https://github.com/paritytech/parity/issues/5754
- [ ] https://github.com/paritytech/parity/issues/5776
- [ ] https://github.com/paritytech/parity/issues/5818
- [ ] https://github.com/paritytech/parity/issues/5990
- [ ] https://github.com/paritytech/parity/issues/6099
- [ ] https://github.com/paritytech/parity/issues/6126
- [ ] https://github.com/paritytech/parity/issues/6172
- [ ] https://github.com/paritytech/parity/issues/6253
- [ ] https://github.com/paritytech/parity/issues/6315
- [ ] https://github.com/paritytech/parity/issues/6362
