### ISSUE TITLE
meta: inactive / long-term core feature-requests collected from parity repository

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-long-term-issues#3]
The following tickets are moved here from paritytech/parity. 

If you work on any of the enhancements, reopen the issue, assign to your self and attach it to a milestone.

- [ ] [#27](https://github.com/paritytech/parity/issues/27) SecureFixedHash
- [ ] [#147](https://github.com/paritytech/parity/issues/147) Blockchain database pruning
- [ ] [#542](https://github.com/paritytech/parity/issues/542) Parity PPA
- [ ] [#620](https://github.com/paritytech/parity/issues/620) Better control over gas-price acceptance
- [ ] [#646](https://github.com/paritytech/parity/issues/646) Peer rating and reputation system
- [ ] [#765](https://github.com/paritytech/parity/issues/765) RESTful interface module
- [ ] [#814](https://github.com/paritytech/parity/issues/814) Light-client Wire Protocol Implementation
- [ ] [#816](https://github.com/paritytech/parity/issues/816) Trie lookups are able to farm from network when missing node
- [ ] [#884](https://github.com/paritytech/parity/issues/884) Pub/Sub RPC feature
- [ ] [#947](https://github.com/paritytech/parity/issues/947) Deny expensive RPC queries
- [ ] [#999](https://github.com/paritytech/parity/issues/999) 100% static binary
- [ ] [#1184](https://github.com/paritytech/parity/issues/1184) Very Fat DB
- [ ] [#1235](https://github.com/paritytech/parity/issues/1235) Dapps Permissions
- [ ] [#1294](https://github.com/paritytech/parity/issues/1294) Build hardening
- [ ] [#1295](https://github.com/paritytech/parity/issues/1295) Reverse sync algorithm
- [ ] [#1327](https://github.com/paritytech/parity/issues/1327) Heartbeats on JSON-RPC WebSockets.
- [ ] [#1425](https://github.com/paritytech/parity/issues/1425) FreeBSD build
- [ ] [#1966](https://github.com/paritytech/parity/issues/1966) TransactionQueue improvements
- [ ] [#1987](https://github.com/paritytech/parity/issues/1987) RPCs/UI for inspecting individual miner's rates
- [ ] [#2066](https://github.com/paritytech/parity/issues/2066) Port CLI to clap
- [ ] [#2097](https://github.com/paritytech/parity/issues/2097) Named column families
- [ ] [#2235](https://github.com/paritytech/parity/issues/2235) Implement RPCs for light client
- [ ] [#2319](https://github.com/paritytech/parity/issues/2319) \"eager\" journalling algorithm
- [ ] [#2424](https://github.com/paritytech/parity/issues/2424) Check if there is enough space on disk before starting a migration
- [ ] [#2452](https://github.com/paritytech/parity/issues/2452) Prioritize mined block
- [ ] [#2458](https://github.com/paritytech/parity/issues/2458) Disable IPC at runtime
- [ ] [#2608](https://github.com/paritytech/parity/issues/2608) Make light and refcounted pruning work with --pruning-history param
- [ ] [#2831](https://github.com/paritytech/parity/issues/2831) Handle low bandwidth connections
- [ ] [#2913](https://github.com/paritytech/parity/issues/2913) Config options without CLI behind them
- [ ] [#3200](https://github.com/paritytech/parity/issues/3200) Devp2p Topic Discovery
- [ ] [#3202](https://github.com/paritytech/parity/issues/3202) Make P2P interface abstract over multiple implementations
- [ ] [#3205](https://github.com/paritytech/parity/issues/3205) Split ethcore crate up into multiple parts
- [ ] [#3294](https://github.com/paritytech/parity/issues/3294) Sort manifests both by peer count and recency
- [ ] [#3497](https://github.com/paritytech/parity/issues/3497) Use dynamic column families for efficiency and database adaptability
- [ ] [#3734](https://github.com/paritytech/parity/issues/3734) LES: per-peer buffer parameters
- [ ] [#3744](https://github.com/paritytech/parity/issues/3744) LES: use persistent peer IDs to avoid buffer flow cheating
- [ ] [#3834](https://github.com/paritytech/parity/issues/3834) Record whether warp-sync was ever used
- [ ] [#3989](https://github.com/paritytech/parity/issues/3989) Exposed Dapps accounts should persist between dapps upgrades
- [ ] [#4105](https://github.com/paritytech/parity/issues/4105) Dapps Elevated Privileges
- [ ] [#4116](https://github.com/paritytech/parity/issues/4116) Define and enforce invariants of JournalDB
- [ ] [#4124](https://github.com/paritytech/parity/issues/4124) Node crawler
- [ ] [#4172](https://github.com/paritytech/parity/issues/4172) Feature - expose state and chaindata via ipfs-http-api
- [ ] [#4251](https://github.com/paritytech/parity/issues/4251) Light client (LES/PIP) support
- [ ] [#4324](https://github.com/paritytech/parity/issues/4324) Rollback database to the specific block/hash (cli command)
- [ ] [#4474](https://github.com/paritytech/parity/issues/4474) Cleanup Dapps & UI servers
- [ ] [#4500](https://github.com/paritytech/parity/issues/4500) Trezor hardware wallet support
- [ ] [#4529](https://github.com/paritytech/parity/issues/4529) Feature request: include own(out of block size) transaction queue into a pending state
- [ ] [#4721](https://github.com/paritytech/parity/issues/4721) More flexible chain spec format
- [ ] [#4727](https://github.com/paritytech/parity/issues/4727) Optimistic snapshot creation
- [ ] [#4758](https://github.com/paritytech/parity/issues/4758) Detect & notify about insufficient free storage space
- [ ] [#4830](https://github.com/paritytech/parity/issues/4830) Feature-request: batch import of blocks (but not necessarily a valid chain) 
- [ ] [#4842](https://github.com/paritytech/parity/issues/4842) Parity-as-a-library
- [ ] [#4858](https://github.com/paritytech/parity/issues/4858) Trace & Fat DB module improvement suggestions
- [ ] [#4897](https://github.com/paritytech/parity/issues/4897) Claymore stratum dialect
- [ ] [#4969](https://github.com/paritytech/parity/issues/4969) Default chain file
- [ ] [#4978](https://github.com/paritytech/parity/issues/4978) Estimation work packages in Stratum
- [ ] [#5001](https://github.com/paritytech/parity/issues/5001) Make Dapps server light-client friendly
- [ ] [#5427](https://github.com/paritytech/parity/issues/5427) Warp/Light-friendly Authority Contract chains
- [ ] [#5687](https://github.com/paritytech/parity/issues/5687) Feature request: Clique/Rinkeby PoA testnet support
- [ ] [#5878](https://github.com/paritytech/parity/issues/5878) Can not choose network interface
- [ ] [#6010](https://github.com/paritytech/parity/issues/6010) Allow warp syncing for light clients
- [ ] [#6055](https://github.com/paritytech/parity/issues/6055) WASM: Solidity->wasm compiler 
- [ ] [#6056](https://github.com/paritytech/parity/issues/6056) WASM MVP
- [ ] [#6138](https://github.com/paritytech/parity/issues/6138) Whisper CLI
- [ ] [#6202](https://github.com/paritytech/parity/issues/6202) `parity_call` light client implementation
- [ ] [#6235](https://github.com/paritytech/parity/issues/6235) Include epoch transition proofs in block export
- [ ] [#6324](https://github.com/paritytech/parity/issues/6324) Improve container support.
- [ ] [#6351](https://github.com/paritytech/parity/issues/6351) Instant finality mode

**Comment by tymat** [comment]
Any plans on FreeBSD support?
